-- Gym Management System Database Schema
CREATE DATABASE IF NOT EXISTS gym_system;
USE gym_system;

-- Users table for admin and staff accounts
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'staff') DEFAULT 'staff',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Staff permissions table
CREATE TABLE staff_permissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    dashboard_access BOOLEAN DEFAULT FALSE,
    clients_access BOOLEAN DEFAULT FALSE,
    gym_access BOOLEAN DEFAULT FALSE,
    pos_access BOOLEAN DEFAULT FALSE,
    reports_access BOOLEAN DEFAULT FALSE,
    packages_items_access BOOLEAN DEFAULT FALSE,
    social_media_access BOOLEAN DEFAULT FALSE,
    settings_access BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Clients table
CREATE TABLE clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    family_name VARCHAR(100),
    phone VARCHAR(20) NOT NULL,
    gender ENUM('male', 'female') NOT NULL,
    referral VARCHAR(50),
    referral_other TEXT,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Packages table
CREATE TABLE packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    duration INT NOT NULL, -- in days
    currency ENUM('USD', 'LBP') DEFAULT 'USD',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Items table for POS
CREATE TABLE items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    stock INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Client packages (subscriptions)
CREATE TABLE client_packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_id INT,
    package_id INT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status ENUM('active', 'expired') DEFAULT 'active',
    payment_amount DECIMAL(10, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    FOREIGN KEY (package_id) REFERENCES packages(id)
);

-- Attendance table
CREATE TABLE attendance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_id INT,
    check_in_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    package_id INT,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    FOREIGN KEY (package_id) REFERENCES packages(id)
);

-- POS sales
CREATE TABLE pos_sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    item_id INT,
    quantity INT NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    currency ENUM('USD', 'LBP') DEFAULT 'LBP',
    client_id INT NULL,
    sale_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    refunded BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL
);

-- Debts table
CREATE TABLE debts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_id INT,
    item_id INT,
    amount DECIMAL(10, 2) NOT NULL,
    paid BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paid_date DATETIME NULL,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(id)
);

-- Expenses table
CREATE TABLE expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency ENUM('USD', 'LBP') DEFAULT 'USD',
    expense_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Package sales for dashboard
CREATE TABLE package_sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_package_id INT,
    amount DECIMAL(10, 2) NOT NULL,
    currency ENUM('USD', 'LBP') DEFAULT 'USD',
    sale_date DATE NOT NULL,
    FOREIGN KEY (client_package_id) REFERENCES client_packages(id)
);

-- WhatsApp messages log
CREATE TABLE whatsapp_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_id INT,
    message TEXT,
    target_group VARCHAR(50),
    sent_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

-- Insert default admin user (password: admin123)
-- This hash is generated by PHP password_hash('admin123', PASSWORD_DEFAULT)
INSERT INTO users (username, password, role) VALUES 
('admin', '$2y$10$YourHashHere', 'admin');

-- NOTE: After importing this SQL, run setup.php to fix the admin password
-- Access: http://localhost/gym_system/setup.php

-- Give admin full permissions
INSERT INTO staff_permissions (user_id, dashboard_access, clients_access, gym_access, pos_access, reports_access, packages_items_access, social_media_access, settings_access) 
VALUES (1, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
